# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure

pool:
  vmImage: 'windows-latest'
  
variables:
  solution: './static/Builds/VisualStudio2019/static.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  
steps:
- task: NuGetToolInstaller@1

- powershell: (New-Object System.Net.WebClient).DownloadFile("https://d30pueezughrda.cloudfront.net/juce/juce-5.4.5-windows.zip", "$pwd/juce.zip")
  displayName: 'Download JUCE'
  
- powershell: Expand-Archive ./juce.zip
  displayName: 'unzip JUCE'
  
- powershell: ./juce/JUCE/Projucer.exe --resave ./static/static.jucer
  displayName: 'rebuild macOS and Windows targets'
- powershell: ls /
- powershell: ls /Builds
- powershell: ls
- powershell: ls ./static
- powershell: ls ./static/Builds
- powershell: ls ./static/Builds/VisualStudio2019

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
